Updated - CICD md

diff --git a/.github/workflows/prod-deploy.yml b/.github/workflows/prod-deploy.yml
--- a/.github/workflows/prod-deploy.yml
+++ b/.github/workflows/prod-deploy.yml
@@ -1,77 +1,107 @@
-name: Build and Deploy - PROD
+name: Build and Deploy - DEV
 on:
-  push:
-    branches:
-      - prod
-
   workflow_dispatch:
+  push:
+    branches: [ "prod" ]
+  pull_request:
+    branches: [ "prod" ]
 
 jobs:
-  init_job:
+  precommit:
     runs-on: ubuntu-latest
     steps:
-      - name: prod_deploy
-        run: echo "prod here"
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Install dependencies
+        run: |
+          python3 -m pip install --upgrade pip
+          pip3 install pre-commit
+          pre-commit install
+      - name: Run pre-commit
+        run: pre-commit run --files ./bot_service/src/backend/*
+
+  run_tests:
+    runs-on: ubuntu-latest
+    # needs: precommit
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Install dependencies
+        run: |
+          python3 -m pip install --upgrade pip
+          pip3 install -r bot_service/src/backend/requirements.txt
+          pip3 install pytest
+      - name: Run tests
+        run: |
+          pytest -v ./bot_service/src/backend/tests/
+
+  fetch_latest_changes:
+    runs-on: ubuntu-latest
+    needs: [run_tests, precommit]
+    if: github.event_name == 'push'
+    steps:
+      - name: Fetch latest changes
+        uses: appleboy/ssh-action@v1.0.3
+        env:
+          REPO_PATH_DEV: ${{ secrets.REPO_PATH_DEV }}
+        with:
+          host: ${{ secrets.HOST_DEV }}
+          username: ${{ secrets.USERNAME_DEV }}
+          key: ${{ secrets.SSH_KEY_DEV }}
+          script: |
+            echo "Starting DEV deployment.."
+            cd ${{ secrets.REPO_PATH_DEV }}
+            ./deploy.sh fetch_latest_changes prod
 
 
-  # fetch_latest_changes:
-  #   runs-on: ubuntu-latest
-  #   needs: init_job
-  #   steps:
-  #     - name: Fetch latest changes
-  #     uses: appleboy/ssh-action@v1.0.3
-  #     with:
-  #       host: ${{ secrets.HOST_PROD }}
-  #       username: ${{ secrets.USERNAME_PROD }}
-  #       key: ${{ secrets.SSH_KEY_PROD }}
-  #       script: |
-  #         echo "Starting PROD deployment.."
-  #         cd ${{ env.REPO_PATH_DEV }}
-  #         ./deploy.sh fetch_latest_changes prod
+  build_deploy:
+    runs-on: ubuntu-latest
+    needs: fetch_latest_changes
+    if: github.event_name == 'push'
+    steps:
+      - name: Build docker containers
+        uses: appleboy/ssh-action@v1.0.3
+        env:
+          REPO_PATH_DEV: ${{ secrets.REPO_PATH_DEV }}
+        with:
+          host: ${{ secrets.HOST_DEV }}
+          username: ${{ secrets.USERNAME_DEV }}
+          key: ${{ secrets.SSH_KEY_DEV }}
+          script: |
+            echo "Starting DEV deployment build.."
+            cd ${{ secrets.REPO_PATH_DEV }}
+            ./deploy.sh deploy_ci prod
 
-  # build_deploy:
-  #   runs-on: ubuntu-latest
-  #   needs: rebuild_containers
-  #   steps:
-  #     - name: Build docker containers
-  #     uses: appleboy/ssh-action@v1.0.3
-  #     with:
-  #       host: ${{ secrets.HOST_PROD }}
-  #       username: ${{ secrets.USERNAME_PROD }}
-  #       key: ${{ secrets.SSH_KEY_PROD }}
-  #       script: |
-  #         echo "Starting PROD deployment build.."
-  #         cd ${{ env.REPO_PATH_DEV }}
-  #         ./deploy.sh deploy_ci prod
-    
-  # health_checks:
-  #   runs-on: ubuntu-latest
-  #   needs: build_deploy
-  #   steps:  
-  #   - name: Perform health checks
-  #     uses: appleboy/ssh-action@v1.0.3
-  #     with:
-  #       host: ${{ secrets.HOST_PROD }}
-  #       username: ${{ secrets.USERNAME_PROD }}
-  #       key: ${{ secrets.SSH_KEY_PROD }}
-  #       script: |
-  #         docker ps 
-          
-  #         echo "Sleeping for 20 seconds until containers are up.."
-  #         sleep 20
 
-  #         BACKEND_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8081/api/health)
+  health_checks:
+    runs-on: ubuntu-latest
+    needs: build_deploy
+    if: github.event_name == 'push'
+    steps:
+      - name: Perform health checks
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.HOST_DEV }}
+          username: ${{ secrets.USERNAME_DEV }}
+          key: ${{ secrets.SSH_KEY_DEV }}
+          script: |
+            docker ps
 
-  #         if [ $BACKEND_CODE!="200" ] 
-  #         then
-  #             echo "FAILURE, backend not reachable"
-  #             exit 1
-  #         fi
+            echo "Sleeping for 20 seconds until containers are up.."
+            sleep 20
 
-  #         FRONTEND_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3001)
+            BACKEND_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8082/api/health)
 
-  #         if [ $FRONTEND_CODE!="200" ] 
-  #         then
-  #             echo "FAILURE, frontend not reachable"
-  #             exit 1
-  #         fi
+            if [ $BACKEND_CODE != 200 ]
+            then
+                echo "FAILURE with status $BACKEND_CODE, backend not reachable"
+                exit 1
+            fi
+
+            FRONTEND_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3001)
+
+            if [ $FRONTEND_CODE != 200 ]
+            then
+                echo "FAILURE with status $FRONTEND_CODE, frontend not reachable"
+                exit 1
+            fi
